"""nerf CLI: validate and generate nerf tools."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Annotated

import typer

from nerftools import BUILTIN_MANIFESTS_DIR as _DEFAULT_MANIFESTS_DIR

if TYPE_CHECKING:
    from nerftools.manifest import NerfManifest

app = typer.Typer(
    name="nerf",
    help="Build and manage nerf tools: defanged, scoped wrappers for agent use.",
    no_args_is_help=True,
)

_VALID_TARGETS = ("bin", "skills", "claude-plugin")


def _resolve_config_manifests(config_manifests: list[str], config_path: Path | None) -> list[Path]:
    """Resolve manifest paths from config relative to the config file's directory."""
    if not config_manifests:
        return []
    base = config_path.parent if config_path is not None else Path.cwd()
    return [(base / m).resolve() for m in config_manifests]


def _load_manifests(
    user_manifests: list[Path],
    *,
    no_default: bool,
) -> list[NerfManifest]:
    from nerftools.manifest import ManifestError, load_manifest, merge_manifests

    paths: list[Path] = []
    if not no_default and _DEFAULT_MANIFESTS_DIR.exists():
        for f in sorted(_DEFAULT_MANIFESTS_DIR.iterdir()):
            if f.suffix == ".yaml" and f.is_file():
                paths.append(f)

    paths.extend(user_manifests)

    loaded = []
    errors: list[str] = []
    for p in paths:
        try:
            loaded.append(load_manifest(p))
        except ManifestError as e:
            errors.append(str(e))

    if errors:
        for err in errors:
            typer.echo(f"Error: {err}", err=True)
        raise typer.Exit(1)

    return merge_manifests(loaded)


@app.command()
def validate(
    manifests: Annotated[list[Path] | None, typer.Argument(help="Manifest files to validate")] = None,
    no_default: Annotated[bool, typer.Option("--no-default", help="Skip built-in manifests")] = False,
    config_path: Annotated[
        Path | None,
        typer.Option(
            "--config", "-c",
            help="Path to a nerf config file. Validated alongside manifests.",
        ),
    ] = None,
) -> None:
    """Parse and validate manifests. Reports errors. No output files."""
    from nerftools.config import ConfigError, load_config

    try:
        config = load_config(config_path)
    except ConfigError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    # Merge config manifests (resolved relative to config file) with positional args.
    all_manifests = _resolve_config_manifests(config.defaults.manifests, config_path)
    all_manifests.extend(manifests or [])

    loaded = _load_manifests(all_manifests, no_default=no_default)

    if not loaded:
        typer.echo("No manifests to validate.", err=True)
        raise typer.Exit(1)

    total_tools = sum(len(m.tools) for m in loaded)
    typer.echo(f"Valid: {len(loaded)} package(s), {total_tools} tool(s)")


@app.command()
def generate(
    manifests: Annotated[list[Path] | None, typer.Argument(help="Additional manifest files")] = None,
    target: Annotated[
        list[str] | None,
        typer.Option("--target", help=f"Output target ({', '.join(_VALID_TARGETS)})"),
    ] = None,
    output: Annotated[Path, typer.Option("--outdir", help="Output directory")] = Path("."),
    no_default: Annotated[bool, typer.Option("--no-default", help="Skip built-in manifests")] = False,
    keep_existing: Annotated[
        bool, typer.Option("--keep-existing", help="Preserve files in outdir not generated by this run")
    ] = False,
    config_path: Annotated[
        Path | None,
        typer.Option(
            "--config", "-c",
            help="Path to a nerf config file (package identity, per-target settings). "
            "Optional; built-in defaults are used when omitted.",
        ),
    ] = None,
) -> None:
    """Generate output from manifests for one or more targets."""
    from nerftools.config import ConfigError, load_config

    if not target:
        typer.echo("Error: at least one --target is required", err=True)
        raise typer.Exit(1)

    for t in target:
        if t not in _VALID_TARGETS:
            typer.echo(f"Error: unknown target '{t}' (valid: {', '.join(_VALID_TARGETS)})", err=True)
            raise typer.Exit(1)

    try:
        config = load_config(config_path)
    except ConfigError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    prefix = config.defaults.prefix

    # Merge config manifests (resolved relative to config file) with positional args.
    all_manifests = _resolve_config_manifests(config.defaults.manifests, config_path)
    all_manifests.extend(manifests or [])

    loaded = _load_manifests(all_manifests, no_default=no_default)

    if not loaded:
        typer.echo("No manifests to generate from.", err=True)
        raise typer.Exit(1)

    for t in target:
        if t == "bin":
            from nerftools.builder import build_scripts

            written = build_scripts(loaded, output, keep_existing=keep_existing, prefix=prefix)
            for path in written:
                typer.echo(f"  {path}")

        elif t == "skills":
            from nerftools.skill import build_skills

            written = build_skills(loaded, output, keep_existing=keep_existing, prefix=prefix)
            for path in written:
                typer.echo(f"  {path}")

        elif t == "claude-plugin":
            from nerftools.config import resolve_claude_plugin_meta
            from nerftools.formats import build_claude_plugin

            plugin_meta, marketplace_meta = resolve_claude_plugin_meta(config)

            written = build_claude_plugin(
                loaded,
                output,
                plugin_meta,
                prefix=prefix,
                marketplace_meta=marketplace_meta,
            )
            for path in written:
                typer.echo(f"  {path}")
