"""nerf CLI: validate and generate nerf tools."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Annotated

import typer

from nerftools import BUILTIN_MANIFESTS_DIR as _DEFAULT_MANIFESTS_DIR

if TYPE_CHECKING:
    from nerftools.manifest import NerfManifest

app = typer.Typer(
    name="nerf",
    help="Build and manage nerf tools: defanged, scoped wrappers for agent use.",
    no_args_is_help=True,
)

_VALID_TARGETS = ("bin", "skills", "claude-plugin")


def _load_manifests(
    user_manifests: list[Path],
    *,
    no_default: bool,
) -> list[NerfManifest]:
    from nerftools.manifest import ManifestError, load_manifest, merge_manifests

    paths: list[Path] = []
    if not no_default and _DEFAULT_MANIFESTS_DIR.exists():
        for f in sorted(_DEFAULT_MANIFESTS_DIR.iterdir()):
            if f.suffix == ".yaml" and f.is_file():
                paths.append(f)

    paths.extend(user_manifests)

    loaded = []
    errors: list[str] = []
    for p in paths:
        try:
            loaded.append(load_manifest(p))
        except ManifestError as e:
            errors.append(str(e))

    if errors:
        for err in errors:
            typer.echo(f"Error: {err}", err=True)
        raise typer.Exit(1)

    return merge_manifests(loaded)


@app.command()
def validate(
    manifests: Annotated[list[Path] | None, typer.Argument(help="Manifest files to validate")] = None,
    no_default: Annotated[bool, typer.Option("--no-default", help="Skip built-in manifests")] = False,
) -> None:
    """Parse and validate manifests. Reports errors. No output files."""
    loaded = _load_manifests(manifests or [], no_default=no_default)

    if not loaded:
        typer.echo("No manifests to validate.", err=True)
        raise typer.Exit(1)

    total_tools = sum(len(m.tools) for m in loaded)
    typer.echo(f"Valid: {len(loaded)} package(s), {total_tools} tool(s)")


@app.command()
def generate(
    manifests: Annotated[list[Path] | None, typer.Argument(help="Additional manifest files")] = None,
    target: Annotated[
        list[str] | None,
        typer.Option("--target", help=f"Output target ({', '.join(_VALID_TARGETS)})"),
    ] = None,
    output: Annotated[Path, typer.Option("--outdir", help="Output directory")] = Path("."),
    no_default: Annotated[bool, typer.Option("--no-default", help="Skip built-in manifests")] = False,
    keep_existing: Annotated[
        bool, typer.Option("--keep-existing", help="Preserve files in outdir not generated by this run")
    ] = False,
    prefix: Annotated[str, typer.Option("--prefix", help="Prefix prepended to every tool name")] = "nerf-",
) -> None:
    """Generate output from manifests for one or more targets."""
    if not target:
        typer.echo("Error: at least one --target is required", err=True)
        raise typer.Exit(1)

    for t in target:
        if t not in _VALID_TARGETS:
            typer.echo(f"Error: unknown target '{t}' (valid: {', '.join(_VALID_TARGETS)})", err=True)
            raise typer.Exit(1)

    loaded = _load_manifests(manifests or [], no_default=no_default)

    if not loaded:
        typer.echo("No manifests to generate from.", err=True)
        raise typer.Exit(1)

    for t in target:
        if t == "bin":
            from nerftools.builder import build_scripts

            written = build_scripts(loaded, output, keep_existing=keep_existing, prefix=prefix)
            for path in written:
                typer.echo(f"  {path}")

        elif t == "skills":
            from nerftools.skill import build_skills

            written = build_skills(loaded, output, keep_existing=keep_existing, prefix=prefix)
            for path in written:
                typer.echo(f"  {path}")

        elif t == "claude-plugin":
            from nerftools.formats import build_claude_plugin

            written = build_claude_plugin(loaded, output, prefix=prefix)
            for path in written:
                typer.echo(f"  {path}")
